In [14]:
import numpy as np
import pandas as pd


In [12]:
lista_mixta = [1, "Python", 3.14, 55]

In [22]:
lista_mixta

[1, 'Python', 3.14, 55]

In [2]:
for i in lista_mixta:
    print(type(i))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'bool'>


In [3]:
type(lista_mixta)

list

In [7]:
array_mixto = np.array(lista_mixta)

In [11]:
print(array_mixto)

['1' 'Python' '3.14' 'True']


In [17]:
array_mixto.dtype

dtype('<U32')

In [8]:
type(array_mixto)

numpy.ndarray

In [9]:
for i in array_mixto:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [10]:
array_int = np.array([1, 2, 3, 4, 5])

for i in array_int:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [15]:
df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv")

Estructuras

In [19]:
lista_1 = [1,2,3,4,5]

In [20]:
array_1 = np.array(lista_1)

In [21]:
array_1

array([1, 2, 3, 4, 5])

In [26]:
array_1.shape

(5,)

In [23]:
lista_2 = [6,7,8,9,10]

In [24]:
array_2 = np.array([lista_1, lista_2])
array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
array_2.shape

(2, 5)

In [28]:
lista_3 = [11,12,13,14,15]

In [31]:
array_3 = np.array([array_2, array_2])
array_3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [32]:
array_3.shape

(2, 2, 5)

In [33]:
array_4 = np.array([array_3, array_3])
array_4

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [34]:
array_4.shape

(2, 2, 2, 5)

Creación de ndarrays